### ISSUE TITLE
"invalid memory address or nil pointer dereference" is valid error

### ISSUE THREAD

**Issue by Lupus** [lainio/err2#1]
I get no stack traces as "invalid memory address or nil pointer dereference" is a valid `error` and gets wrapped by `err2.Returnf`, loosing stack trace and making this bug impossible to debug. Is that expected?

**Comment by techlab-lainio** [comment]
Hello @Lupus, and thank you so much! You were correct; It was a regression bug. 

I have fixed the bug in v0.8.1 where `runtime.Error` types are left as panics and not treated as `error` anymore.

I'm very sorry that I reply so late. I have been eagerly waiting for Go generics that I'm to be able to finish the project so that I can say I'm comfortable with the API and the implementation. It has been tagged as an experimental project until then, but not anymore. Now I will maintain it with the resources I have.

Once again, thank you for the issue. You have been the first!

**Comment by Lupus** [comment]
Cool, thanks!
