### ISSUE TITLE
Handle decamels the function name

### ISSUE THREAD

**Issue by nathaniel-lehrer-ib** [lainio/err2#10]
Hello Lainio,

Thanks so much for putting this library together! We've been using it for several months now in our project. It has made error handling much better :)

I see there is a new method "Handle" which automatically annotates the error with the method's name. This is really helpful! One thing I noticed was that it decamels the method name. It would be nice to preserve the original so that it can be easily searched for without having to reassemble it. In terms of readability it still suffers anyway because it ends up keeping the pointer notation, ie "(*my struct) my method: some error message".

https://github.com/lainio/err2/blob/92c5df1c01b5ed83d8fdcb01e548e914e4c3b798/internal/handler/handler.go#L241

Thoughts?

**Comment by lainio** [comment]
Hello,

Thank you so much for the kind words and the feedback! Highly appreciate.

My first thought about your request is that I need to do something about that 👍 

This was the first implementation to get more information about the subject. During the first implementation, I noticed those marginal cases like anonymous functions (`.Func1`) and how to treat the actual package name (`uuid.New()` -> "uuid new" is better than just "new", but not always!). Our use cases are covered by simple decameling because we rely on logs for `err2`'s error trace functionality and assertations. But yes, I'll look for the next-best solution and hopefully a simple API. 

My gut feeling is that I'll bring a `formatter` interface and a few default implementations like `decamel` and `noop`. I will cover this in the next release.

Once again, thanks for the feedback!

**Comment by lainio** [comment]
FYI PR #11 now fixes the decamel bugs. I'll think I will release it quite soon, but before that, I am trying to think of a new config API where `err2` callers could bring their own formatters as well. Letting you know..

**Comment by nathaniel-lehrer-ib** [comment]
Thanks for your response and continued development on this!

**Comment by lainio** [comment]
There is now a new version, v0.8.13. Please check it out.

**Comment by lainio** [comment]
I'm preparing to close this issue. Here's an additional example of how to implement and set your own `Formatter`:
```go
	err2.SetFormatter(&formatter.Formatter{
		DoFmt: func(raw string) string {
			return "my ERROR: " + raw
		},
	})
```
Anybody please let me know if you find any bugs or annoying things in the formatted API. Thanks!

**Comment by nathaniel-lehrer-ib** [comment]
Thanks for the update! Will let you know if anything else comes up :D

**Comment by lainio** [comment]
The new API and fix are working. Fixing the issue.
